### ISSUE TITLE
visualizer missing

### ISSUE THREAD

**Issue by vendelin8** [smiley1983/lightriders-standalone#1]
Hi,

I tried the module, but it says:
ImportError: No module named visualizer.visualize_locally
Should I download something else?

Cheers

**Comment by smiley1983** [comment]
Yes, you're right, there's currently no visualizer. I'm not sure if I'll get time to write one.

If you use the "--nolaunch" flag when running playgame.py, it won't show this error.

If anyone wants to write the visualizer, look at this code for a different Tron game which I built on top of the same underlying system:
[tron_tcp](https://github.com/smiley1983/ants-tcp/tree/master/tron/tron_tcp)

I'm not sure how much work would be involved in getting it running.

**Comment by vendelin8** [comment]
Okay, thanks!

**Comment by smiley1983** [comment]
Hi, I had failed to understand that it crashed even with the --nolaunch option. I've updated it so it doesn't have the offending line.

I also made another important change - it was interpreting the results backwards, so I encourage updating to the latest version!
